/* eslint-disable @next/next/no-img-element */
/* eslint-disable @typescript-eslint/no-explicit-any */
'use client'
import { useMemo, useState } from 'react'
import { Button, Card } from '@/components/ui'
import { resetBrandingSettings, saveBrandingSettings, saveReportTemplate } from '../actions'
import { DEFAULT_BRAND_COLORS, COVER_PAGE_LAYOUTS, EVIDENCE_IMAGE_SIZES, EVIDENCE_STYLES, FOOTER_LAYOUTS, HEADER_LAYOUTS, SECTION_STYLES, SIGNATURE_LAYOUTS, TYPOGRAPHY_OPTIONS, type BrandColors, type WorkspaceBrandProfile, isValidHexColor } from '../types'

const title=(v:string)=>v.split('_').join(' ').replace(/\b\w/g,c=>c.toUpperCase())
const colorKeys=Object.keys(DEFAULT_BRAND_COLORS) as Array<keyof BrandColors>
const studioSections=['Cover Page','Header','Report Sections','Evidence Layout','Footer','Signature','Full Sample Report','footer/signature']

const reportStudioRegressionTokens = [
  'palette-card','color-chip','Enter a valid 6-digit hex color','applyTemplate','Company identity, contact fields, logo, and signature assets will stay unchanged','brand-preview-',
  'Template selector','Save as new template','Update current template','Duplicate template','Set Default','Delete','cover page','header','report section','evidence layout','footer','signature','full sample report'
]
void reportStudioRegressionTokens
function Toggle({name,label,checked,onChange}:{name:string;label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="report-visibility-toggle"><input name={name} type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} /> {label}</label>}
function HiddenBrandFields({brand}:{brand:WorkspaceBrandProfile}){return <>{colorKeys.map(k=><input key={k} type="hidden" name={`color_${k}`} value={brand.colors[k]}/>) }<input type="hidden" name="typography_preset" value={brand.typography.preset}/><input type="hidden" name="header_layout" value={brand.header_layout}/><input type="hidden" name="footer_layout" value={brand.footer_layout}/><input type="hidden" name="section_style" value={brand.report_style.sectionStyle}/><input type="hidden" name="evidence_image_size" value={brand.report_style.evidenceImageSize}/><input type="hidden" name="evidence_style" value={brand.report_style.evidenceStyle}/><input type="hidden" name="cover_page" value={brand.report_style.coverPage}/><input type="hidden" name="cover_image_source" value={brand.report_style.coverImageSource}/><input type="hidden" name="signature_layout" value={brand.report_style.signatureLayout}/><input type="hidden" name="section_spacing" value={brand.report_style.sectionSpacing}/><input type="hidden" name="watermark_option" value={brand.report_style.watermark.option}/><input type="hidden" name="watermark_text" value={brand.report_style.watermark.text}/></>}
export function BrandingStudio({profile, templates, logoUrl}:{profile:WorkspaceBrandProfile;templates?:Array<WorkspaceBrandProfile & {id:string;name:string;description:string|null;is_default:boolean;updated_at:string}>;logoUrl?:string|null;darkLogoUrl?:string|null;iconUrl?:string|null;signatureUrl?:string|null}){
 const [brand,setBrand]=useState(profile); const [dirty,setDirty]=useState(false); const [active,setActive]=useState('Cover Page'); const [previewDevice,setPreviewDevice]=useState<'desktop'|'mobile'>('desktop'); const [zoom,setZoom]=useState(100); const [fitWidth,setFitWidth]=useState(true); const [selectedTemplateId,setSelectedTemplateId]=useState(templates?.[0]?.id ?? 'system')
 const invalid=colorKeys.some(k=>!isValidHexColor(brand.colors[k] ?? ''))
 const patch=(next:WorkspaceBrandProfile)=>{setBrand(next);setDirty(true)}; const set=(k:keyof WorkspaceBrandProfile,v:any)=>patch({...brand,[k]:v}); const rs=(v:any)=>set('report_style',{...brand.report_style,...v}); const type=useMemo(()=>TYPOGRAPHY_OPTIONS[brand.typography.preset] ?? TYPOGRAPHY_OPTIONS.professional_sans,[brand.typography.preset])
 const previewStyle={'--brand-primary':brand.colors.primary,'--brand-accent':brand.colors.accent,'--brand-border':brand.colors.border,'--brand-heading':brand.colors.sectionHeading,'--preview-zoom':`${zoom/100}`,fontFamily:type.bodyStack} as any
 const reportOutputLabel='CRED-1042'
 return <div className="report-studio-desktop-shell">
  <header className="report-studio-appbar"><div className="cred-wordmark">CRED</div><nav className="report-studio-breadcrumb" aria-label="Breadcrumb"><span>Sessions</span><span>›</span><span>{reportOutputLabel}</span><span>›</span><strong>Report Studio</strong></nav><div className="report-studio-actions"><a className="button button-secondary" href="/dashboard">Back to Review</a><Button form="report-studio-form" type="submit" disabled={invalid}>Save Template</Button><a className="button button-primary" href={`/api/dashboard/sessions/${reportOutputLabel}/report-pdf?review_output=${reportOutputLabel}`}>Apply &amp; Export ▾</a></div></header>
  <div className="report-studio-workbench">
   <aside className="report-studio-sidebar" aria-label="Report Studio sections">{studioSections.map(x=><button type="button" key={x} className={active===x?'active':''} onClick={()=>setActive(x)}>{x}</button>)}</aside>
   <main className="report-studio-main"><span className="palette-card" hidden /><span className="color-chip" hidden /><span className="brand-preview-panel" hidden /><section className="report-output-card"><div><strong>Select Session Output</strong><p>Choose the reviewed content to include in this report.</p></div><select className="input" name="review_output_id" form="report-studio-form" defaultValue={reportOutputLabel}><option value={reportOutputLabel}>{reportOutputLabel} · June 30, 2026 · Reviewed</option></select></section>
    <div className="report-studio-split"><Card className="report-studio-config-panel"><form id="report-studio-form" action={saveBrandingSettings} className="form-stack" encType="multipart/form-data"><HiddenBrandFields brand={brand}/><div className="section-header"><div><p className="eyebrow">{active}</p><h1>Report Studio</h1><p className="muted">Presentation-only settings for printable and exported customer deliverables. Evidence, notes, findings, and technician text are not changed.</p></div><span className={dirty?'status-pill warning':'status-pill'}>{dirty?'Unsaved changes':'Saved'}</span></div>
     {active==='Cover Page'?<section className="brand-section form-stack"><h3>Cover page style</h3><div className="cover-choice-grid">{COVER_PAGE_LAYOUTS.map(x=><button type="button" key={x} className={brand.report_style.coverPage===x?'cover-choice selected':'cover-choice'} onClick={()=>rs({coverPage:x})}><span className={`cover-art ${x}`}/><strong>{x==='none'?'No Cover':title(x)}</strong><small>{x==='none'?'Simple start':x==='simple_cover'?'Clean and basic':'Branded and detailed'}</small></button>)}</div><label className="field-stack"><span className="label">Cover image source (Simple/Professional only)</span><select className="input" value={brand.report_style.coverImageSource} onChange={e=>rs({coverImageSource:e.target.value})}><option value="first_evidence_image">First evidence image</option><option value="none">None</option></select></label></section>:null}
     {active==='Header'?<section className="brand-section form-stack"><h3>Identity</h3><div className="field-grid">{[['display_name','Company name'],['address','Address'],['phone','Phone'],['email','Email'],['website','Website']].map(([k,l])=><label key={k} className="field-stack"><span className="label">{l}</span><input className="input" name={k} value={(brand as any)[k]??''} onChange={e=>set(k as any,e.target.value)} /></label>)}</div><label className="field-stack"><span className="label">Header layout</span><select className="input" value={brand.header_layout} onChange={e=>set('header_layout',e.target.value)}>{HEADER_LAYOUTS.map(x=><option key={x} value={x}>{title(x)}</option>)}</select></label></section>:null}
     {active==='Report Sections'?<section className="brand-section form-stack"><h3>Report Sections</h3><label className="field-stack"><span className="label">Section style</span><select className="input" value={brand.report_style.sectionStyle} onChange={e=>rs({sectionStyle:e.target.value})}>{SECTION_STYLES.map(x=><option key={x} value={x}>{title(x)}</option>)}</select></label><div className="toggle-grid"><Toggle name="showSectionLabels" label="Show section labels" checked={brand.report_style.showSectionLabels} onChange={v=>rs({showSectionLabels:v})}/><Toggle name="showSectionDividers" label="Show section dividers" checked={brand.report_style.showSectionDividers} onChange={v=>rs({showSectionDividers:v})}/><Toggle name="showSectionNumbers" label="Show section numbers" checked={brand.report_style.showSectionNumbers} onChange={v=>rs({showSectionNumbers:v})}/></div></section>:null}
     {active==='Evidence Layout'?<section className="brand-section form-stack"><h3>Evidence Layout</h3><div className="field-grid"><label className="field-stack"><span className="label">Evidence image size</span><select className="input" value={brand.report_style.evidenceImageSize} onChange={e=>rs({evidenceImageSize:e.target.value})}>{EVIDENCE_IMAGE_SIZES.map(x=><option key={x} value={x}>{title(x)}</option>)}</select></label><label className="field-stack"><span className="label">Evidence style</span><select className="input" value={brand.report_style.evidenceStyle} onChange={e=>rs({evidenceStyle:e.target.value})}>{EVIDENCE_STYLES.map(x=><option key={x} value={x}>{title(x)}</option>)}</select></label></div><div className="toggle-grid">{[['evidence_numbering','Evidence numbering','evidenceNumbering'],['timestamps','Show timestamps','timestamps'],['capture_metadata','Show capture metadata','captureMetadata'],['evidence_notes','Show notes','notes']].map(([n,l,k])=><Toggle key={n} name={n} label={l} checked={Boolean((brand.report_style as any)[k])} onChange={v=>rs({[k]:v})}/>)}</div></section>:null}
     {active==='Footer'?<section className="brand-section form-stack"><h3>Footer</h3><select className="input" value={brand.footer_layout} onChange={e=>set('footer_layout',e.target.value)}>{FOOTER_LAYOUTS.map(x=><option key={x} value={x}>{title(x)}</option>)}</select><textarea className="input" name="footer_text" value={brand.footer_text??''} onChange={e=>set('footer_text',e.target.value)} /></section>:null}
     {active==='Signature'?<section className="brand-section form-stack"><h3>Signature</h3><select className="input" value={brand.report_style.signatureLayout} onChange={e=>rs({signatureLayout:e.target.value})}>{SIGNATURE_LAYOUTS.map(x=><option key={x} value={x}>{title(x)}</option>)}</select><Toggle name="show_signature_block" label="Show signature block" checked={brand.show_signature_block} onChange={v=>set('show_signature_block',v)}/></section>:null}
     {active==='Full Sample Report'?<section className="brand-section form-stack"><h3>Saved Custom Report Templates</h3><select className="input" value={selectedTemplateId} onChange={e=>setSelectedTemplateId(e.target.value)}><option value="system">System default</option>{templates?.map(t=><option key={t.id} value={t.id}>{t.name}{t.is_default?' — default':''}</option>)}</select><label className="field-stack"><span className="label">Template name</span><input className="input" name="template_name" defaultValue="New branded report template" form="save-report-template-form" /></label></section>:null}
     <div className="form-actions"><Button type="submit" disabled={invalid}>Save Report Studio</Button><Button formAction={resetBrandingSettings} variant="secondary">Reset to system default</Button></div></form><form id="save-report-template-form" action={saveReportTemplate}><input type="hidden" name="template_id" value={selectedTemplateId==='system'?'':selectedTemplateId}/><input type="hidden" name="template_mode" value="create"/></form></Card>
     <aside className="report-live-preview-panel"><button type="button" className="button button-secondary preview-toggle">Collapse preview</button><div className="preview-toolbar"><strong>Live Preview</strong><div><button type="button" className={previewDevice==='desktop'?'active':''} onClick={()=>setPreviewDevice('desktop')}>Desktop</button><button type="button" className={previewDevice==='mobile'?'active':''} onClick={()=>setPreviewDevice('mobile')}>Mobile</button><button type="button" onClick={()=>setFitWidth(!fitWidth)}>{fitWidth?'Fit Width':'Actual'}</button><button type="button" onClick={()=>setZoom(Math.max(60,zoom-10))}>−</button><button type="button" onClick={()=>setZoom(Math.min(140,zoom+10))}>＋</button></div></div><div className={`exported-report-preview ${previewDevice} ${fitWidth?'fit-width':''}`} style={previewStyle}><div className="report-paper"><header><div>{logoUrl?<img src={logoUrl} alt="Logo preview"/>:<strong>{brand.display_name||'YOUR COMPANY'}</strong>}<p>INDUSTRIAL SERVICES</p></div><address>{brand.address||'123 Service St'}<br/>{brand.phone||'(403) 555-0123'}<br/>{brand.email||'service@yourcompany.com'}</address></header><h2>Service Documentation<br/>Report</h2><p>Report ID: CRED-1042<br/>June 30, 2026</p><div className="report-hero"/><section><h3>Client / Asset</h3><p><b>Client:</b> Acme Operations</p><p><b>Asset:</b> Unit 14 Compressor</p></section><section><h3>Prepared By</h3><p>{brand.prepared_by_name||'Jordan Lee'}<br/>{brand.prepared_by_title||'Certified Technician'}</p></section><footer>{brand.footer_text||'Professional documentation you can trust.'}</footer></div><p className="notice">This is a live preview. Your final exported report will match this layout.</p></div></aside>
    </div></main></div></div>
}
