import { escapeHtml } from "./html";
import type { ExportBranding } from "./types";

export function buildPrintFooterHtml(params: { organizationName: string; reportId?: string | null; generatedAt: string; branding?: ExportBranding | null }) {
  const brand = params.branding;
  const reportId = params.reportId?.trim() || "Report";
  const name = brand?.display_name?.trim() || params.organizationName;
  const contact = [brand?.phone, brand?.email, brand?.website].filter(Boolean).join(" · ");
  const parts = [escapeHtml(name)];
  if (brand?.show_contact_info !== false && contact) parts.push(escapeHtml(contact));
  if (brand?.footer_text) parts.push(escapeHtml(brand.footer_text));
  if (brand?.show_confidentiality_note) parts.push("Confidential");
  if (brand?.show_report_id !== false) parts.push(escapeHtml(reportId));
  if (brand?.report_style?.showGeneratedByCred) parts.push("Generated by CRED");
  parts.push(`Generated ${escapeHtml(params.generatedAt)}`);
  return `<footer class="print-page-footer branded-report-footer" aria-hidden="true">${parts.map((part) => `<span>${part}</span>`).join("")}</footer>`;
}
