import assert from 'node:assert/strict'
import test from 'node:test'
import { readFileSync } from 'node:fs'

const source = readFileSync(
  'src/features/reports/export/executive-pdf.ts',
  'utf8',
)

test('executive PDF does not expose internal approval state or product attribution', () => {
  assert.doesNotMatch(source, /Generated by CRED/)
  assert.doesNotMatch(source, /\.text\(snapshot\.approval\.status/)
  assert.doesNotMatch(source, /sectionHeading\(doc, "Approval"/)
})

test('executive PDF uses customer-facing completion and closing language', () => {
  assert.match(source, /sectionHeading\(doc, "Report Completion"/)
  assert.match(source, /label: "Completed by"/)
  assert.match(source, /label: "Completed"/)
  assert.match(source, /section\.id === "final-notes" \? "Closing Notes"/)
})

test('documented item pagination keeps the first photo with its item context', () => {
  assert.match(source, /const minimumTogether = item\.mediaIds\.length/)
  assert.match(source, /getPrimaryMediaHeight\(style\)/)
  assert.match(source, /ensureSpace\(doc, Math\.min\(minimumTogether/)
})
