import assert from 'node:assert/strict'
import test from 'node:test'
import { readFileSync } from 'node:fs'

const route = readFileSync('app/api/dashboard/sessions/[id]/report-pdf/route.ts', 'utf8')
const brandCss = readFileSync('src/features/report-studio/rendering/report-brand-css.ts', 'utf8')
const shell = readFileSync('src/features/report-studio/rendering/report-shell.ts', 'utf8')
const cover = readFileSync('src/features/report-studio/rendering/report-cover.ts', 'utf8')
const footer = readFileSync('src/features/report-studio/rendering/report-footer.ts', 'utf8')
const watermark = readFileSync('src/features/report-studio/rendering/report-watermark.ts', 'utf8')
const signatures = readFileSync('src/features/report-studio/rendering/report-signatures.ts', 'utf8')
const evidenceLayout = readFileSync('src/features/report-studio/rendering/report-evidence-layout.ts', 'utf8')

test('report studio rendering helpers live in feature modules, not the route', () => {
  for (const helper of [
    'buildBrandCss',
    'buildReportOpen',
    'buildReportShellClasses',
    'buildReportCoverHtml',
    'buildPrintFooterHtml',
    'buildWatermarkHtml',
    'getWatermarkText',
    'buildApprovalHtml',
  ]) {
    assert.doesNotMatch(route, new RegExp(`function ${helper}\\b`), `${helper} should not be implemented in the route`)
  }

  assert.match(route, /from "@\/features\/report-studio\/rendering\/report-brand-css"/)
  assert.match(route, /from "@\/features\/report-studio\/rendering\/report-shell"/)
  assert.match(route, /from "@\/features\/report-studio\/rendering\/report-cover"/)
  assert.match(route, /from "@\/features\/report-studio\/rendering\/report-footer"/)
  assert.match(route, /from "@\/features\/report-studio\/rendering\/report-signatures"/)
})

test('extracted brand and shell helpers preserve branding output tokens', () => {
  assert.match(brandCss, /body\{font-family:\$\{area\.body_text \?\? type\.bodyStack\};color:\$\{colors\.accent\}\}/)
  assert.match(brandCss, /--brand-primary:\$\{colors\.primary\}/)
  assert.match(brandCss, /sectionHeadingLetterSpacing \|\| "\.08em"/)

  for (const token of ['theme-', 'typography-', 'header-', 'footer-', 'section-', 'evidence-', 'image-', 'signature-']) {
    assert.match(shell, new RegExp(token))
  }
  assert.match(shell, /data-generated-at=/)
  assert.match(shell, /buildWatermarkHtml\(params\.branding\)/)
})

test('extracted cover, footer, watermark, and signature helpers preserve presentation markup', () => {
  assert.match(cover, /class=\"report-cover item branded-cover/)
  assert.match(cover, /Documentation Report/)
  assert.match(cover, /Customer \/ Client/)
  assert.match(cover, /brand-report-logo/)
  assert.match(cover, /helpers\.renderDefinitionRows\(definitionRows\)/)

  assert.match(footer, /print-page-footer branded-report-footer/)
  assert.match(footer, /Generated by CRED/)
  assert.match(footer, /Confidential/)

  assert.match(watermark, /custom_text/)
  assert.match(watermark, /report-watermark watermark-/)
  assert.match(watermark, /aria-hidden=\"true\"/)

  assert.match(signatures, /Formal sign-off/)
  assert.match(signatures, /No signature captured/)
  assert.match(signatures, /typedSignature/)
  assert.match(signatures, /helpers\.renderDefinitionRows\(rows\)/)
  assert.match(evidenceLayout, /ReportImageLightboxOptions/)
})
