import { formatDateTime } from '@/features/sessions'
import type { DeliverableDetailData } from '../data'
import { formatDeliverableStatus, summarizeDeliverableProvenance } from '../data'
import { PrintableChronology } from './PrintableChronology'
import { PrintableEvidenceIndex } from './PrintableEvidenceIndex'
import { PrintableObservationSummary } from './PrintableObservationSummary'
import { RelationshipMapPreview } from './RelationshipMapPreview'

export function DeliverablePrintView({ data }: { data: DeliverableDetailData }) {
  const { deliverable, session, timeZone } = data
  return <main className="deliverable-print-view"><style>{`@media print {.dashboard-frame > nav, .print-actions { display: none !important; } body { background: #fff !important; } .deliverable-print-view { box-shadow: none; margin: 0; padding: 0; } } .deliverable-print-view { background: #fff; color: #111827; max-width: 1040px; margin: 24px auto; padding: 40px; font-family: Arial, sans-serif; } .print-header { border-bottom: 3px solid #111827; margin-bottom: 24px; padding-bottom: 16px; } .print-kicker { color: #4b5563; font-size: 12px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; } .print-meta { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px 24px; margin: 20px 0; } .print-meta dt { color: #4b5563; font-size: 12px; font-weight: 700; text-transform: uppercase; } .print-meta dd { margin: 2px 0 0; } .provenance-note { border: 1px solid #d1d5db; background: #f9fafb; padding: 12px; } .print-table { border-collapse: collapse; width: 100%; } .print-table th, .print-table td { border: 1px solid #d1d5db; padding: 8px; text-align: left; vertical-align: top; } .print-table th { background: #f3f4f6; } .print-observation { border-bottom: 1px solid #d1d5db; break-inside: avoid; padding: 12px 0; } .print-actions { margin-bottom: 16px; }`}</style><div className="print-actions"><p>Use your browser print command to print or save this deliverable as a PDF.</p></div><header className="print-header"><p className="print-kicker">Evidence Workspace Deliverable</p><h1>{deliverable.title} — Version {deliverable.version_number}</h1><p>{session.title}</p></header><dl className="print-meta"><div><dt>Session context</dt><dd>{session.title}</dd></div><div><dt>Deliverable type</dt><dd>{deliverable.deliverable_type}</dd></div><div><dt>Status</dt><dd>{formatDeliverableStatus(deliverable.status)}</dd></div><div><dt>Version</dt><dd>Version {deliverable.version_number}</dd></div><div><dt>Generated</dt><dd>{formatDateTime(deliverable.generated_at, timeZone)}</dd></div>{deliverable.finalized_at ? <div><dt>Finalized</dt><dd>{formatDateTime(deliverable.finalized_at, timeZone)}</dd></div> : null}</dl><p className="provenance-note"><strong>Source-controlled deliverable:</strong> <span className="print-kicker">Source / provenance note</span> {summarizeDeliverableProvenance(deliverable.provenance, deliverable.source_ids)}. This printable view uses the persisted deliverable snapshot.</p>{deliverable.deliverable_type === 'chronology' ? <PrintableChronology content={deliverable.content} /> : null}{deliverable.deliverable_type === 'evidence_index' ? <PrintableEvidenceIndex content={deliverable.content} /> : null}{deliverable.deliverable_type === 'observation_summary' ? <PrintableObservationSummary content={deliverable.content} /> : null}{deliverable.deliverable_type === 'relationship_map' ? <RelationshipMapPreview content={deliverable.content} /> : null}</main>
}
