import Link from 'next/link'
import { formatDateTime } from '@/features/sessions'
import type { DeliverableShareToken, EvidenceDeliverable } from '../data'
import { createEvidenceDeliverableShareLinkFormAction, revokeEvidenceDeliverableShareLinkFormAction, rotateEvidenceDeliverableShareLinkFormAction } from '../actions'
import { deliverableShareStatus, getDeliverableShareUrl, isActiveShareToken } from '../share'

export function DeliverableSharing({ sessionId, deliverable, shareTokens, timeZone, compact = false }: { sessionId: string; deliverable: EvidenceDeliverable; shareTokens: DeliverableShareToken[]; timeZone: string | null; compact?: boolean }) {
  if (deliverable.status !== 'final') return null
  const latest = shareTokens.find((token) => token.deliverable_id === deliverable.id && token.link_kind === 'deliverable') ?? null
  const active = shareTokens.find((token) => token.deliverable_id === deliverable.id && token.link_kind === 'deliverable' && isActiveShareToken(token)) ?? null
  const status = deliverableShareStatus(active ?? latest)
  const url = active ? getDeliverableShareUrl(active.token) : ''
  return <section className="card form-stack" aria-label="Secure share link"><div><p className="eyebrow">Secure share link</p><h3>{compact ? 'Share finalized version' : 'Sharing'}</h3><p className="muted">This link shares this exact finalized version. Newer versions are not shared automatically.</p></div><div className="metadata-list"><div><dt>Status</dt><dd>{status}</dd></div>{latest ? <div><dt>Created</dt><dd>{formatDateTime(latest.created_at, timeZone)}</dd></div> : null}{latest?.expires_at ? <div><dt>Expires</dt><dd>{formatDateTime(latest.expires_at, timeZone)}</dd></div> : null}{latest?.created_by ? <div><dt>Created by</dt><dd>Organization member</dd></div> : null}{latest ? <div><dt>Access</dt><dd>{latest.view_count} views{latest.last_viewed_at ? ` · Last accessed ${formatDateTime(latest.last_viewed_at, timeZone)}` : ''}</dd></div> : null}</div>{active ? <div className="form-stack"><label><span className="sr-only">Secure share link URL</span><input readOnly value={url} /></label><div className="button-row"><Link className="button button-secondary touch-target" href={url}>Open shared view</Link><button className="button button-secondary touch-target" type="button">Copy link</button><form action={revokeEvidenceDeliverableShareLinkFormAction.bind(null, sessionId, deliverable.id, active.id)}><button className="button button-secondary touch-target" type="submit">Revoke access</button></form>{!compact ? <form action={rotateEvidenceDeliverableShareLinkFormAction.bind(null, sessionId, deliverable.id, active.id)}><button className="button button-secondary touch-target" type="submit">Rotate link</button></form> : null}</div></div> : <form action={createEvidenceDeliverableShareLinkFormAction.bind(null, sessionId, deliverable.id)} className="button-row"><button className="button button-primary touch-target" type="submit">Create share link</button></form>}</section>
}
