import type { DeliverableSourceData } from '../service'

export function DeliverableSourceSelector({ sources }: { sources: DeliverableSourceData }) {
  const batches = sources.importBatches ?? []
  return <div className="form-stack"><fieldset className="form-stack"><legend>Source scope</legend><p className="muted">Leave lists unselected to use all reviewed workspace material that passes the safe defaults, or choose specific source records to narrow generation.</p><label className="checkbox-row"><input type="checkbox" name="includeNeedsFollowUpEvidence" /> Include evidence marked needs follow-up</label><label className="checkbox-row"><input type="checkbox" name="includeOutputExcludedEvidence" /> Include output-excluded evidence only if explicitly selected</label><label className="checkbox-row"><input type="checkbox" name="includeAcceptedSuggestions" defaultChecked value="on" /> Include accepted suggestions</label><input type="hidden" name="includeAcceptedSuggestions" value="off" /><label className="checkbox-row"><input type="checkbox" name="includeEditedSuggestions" defaultChecked value="on" /> Include edited suggestions</label><input type="hidden" name="includeEditedSuggestions" value="off" /></fieldset><Selector title="Selected import batches" name="selectedImportBatchIds" rows={batches.map((batch) => ({ id: batch.id, label: `${batch.source_kind} · ${batch.status} · ${batch.file_count} files` }))} /><Selector title="Selected evidence items" name="selectedCaptureItemIds" rows={sources.evidenceItems.map((item) => ({ id: item.id, label: item.original_filename ?? item.technician_note ?? item.ai_summary ?? item.type }))} /><Selector title="Selected factual observations" name="selectedAssertionIds" rows={sources.assertions.map((assertion) => ({ id: assertion.id, label: assertion.statement }))} /><Selector title="Selected timeline events" name="selectedTimelineEventIds" rows={sources.timelineEvents.map((event) => ({ id: event.id, label: event.title }))} /><Selector title="Selected entities" name="selectedEntityIds" rows={sources.entities.map((entity) => ({ id: entity.id, label: `${entity.display_name} (${entity.entity_type})` }))} /></div>
}

function Selector({ title, name, rows }: { title: string; name: string; rows: Array<{ id: string; label: string }> }) {
  return <fieldset className="form-stack"><legend>{title}</legend>{rows.length === 0 ? <p className="muted">No available records.</p> : rows.slice(0, 25).map((row) => <label key={row.id} className="checkbox-row"><input type="checkbox" name={name} value={row.id} /> <span>{row.label}</span></label>)}{rows.length > 25 ? <p className="muted">Showing first 25 deterministic choices; all reviewed material remains included when none are checked.</p> : null}</fieldset>
}
