import Link from 'next/link'
import { formatDateTime } from '@/features/sessions'
import type { getDeliverablesData, EvidenceDeliverable } from '../data'
import { formatDeliverableStatus, formatDeliverableTitle, getDeliverableSourceSummary, summarizeDeliverableContent } from '../data'
import { archiveEvidenceDeliverableFormAction, finalizeEvidenceDeliverableFormAction, generateEvidenceDeliverableFormAction, restoreArchivedDeliverableFormAction } from '../actions'
import { DeliverableCard } from './DeliverableCard'
import { DeliverablePreview } from './DeliverablePreview'
import { DeliverableAssemblyPanel } from './DeliverableAssemblyPanel'
import { DeliverableSharing } from './DeliverableSharing'

export function DeliverablesWorkspace({ data }: { data: Awaited<ReturnType<typeof getDeliverablesData>> }) {
  const deliverablesByType = data.availableTypes.map((type) => ({ ...type, deliverables: sortDeliverables(data.deliverables.filter((deliverable) => deliverable.deliverable_type === type.type && deliverable.status !== 'archived')), archived: sortDeliverables(data.deliverables.filter((deliverable) => deliverable.deliverable_type === type.type && deliverable.status === 'archived')) }))
  return <div className="form-stack"><DeliverableAssemblyPanel data={data} /><section className="workspace-card-grid" aria-label="Available deliverable types">{data.availableTypes.map((type) => <DeliverableCard key={type.type} sessionId={data.session.id} {...type} />)}</section><section className="card detail-card form-stack"><div><p className="eyebrow">Generated deliverables</p><h2>Source-controlled output versions</h2><p className="muted">Generated from reviewed items. Each generated row is retained as an immutable deliverable version.</p></div>{data.deliverables.length === 0 ? <p className="muted">No deliverables generated yet.</p> : deliverablesByType.map((group) => <section key={group.type} className="form-stack" aria-label={`${group.title} versions`}><div className="section-header"><div><h3>{group.title}</h3><p className="muted">Generate new version to create a new controlled snapshot from the current workspace data.</p></div><form action={generateEvidenceDeliverableFormAction.bind(null, data.session.id)}><input type="hidden" name="deliverable_type" value={group.type} /><button className="button button-secondary touch-target" type="submit">Generate new version</button></form></div>{group.deliverables.filter((deliverable) => deliverable.status === 'final').map((deliverable) => <DeliverableVersionCard key={deliverable.id} deliverable={deliverable} sessionId={data.session.id} timeZone={data.timeZone} current shareTokens={data.shareTokens} />)}{group.deliverables.filter((deliverable) => deliverable.status === 'draft').map((deliverable) => <DeliverableVersionCard key={deliverable.id} deliverable={deliverable} sessionId={data.session.id} timeZone={data.timeZone} />)}{group.deliverables.some((deliverable) => deliverable.status === 'superseded') ? <details className="card form-stack"><summary className="touch-target"><strong>Version history</strong></summary>{group.deliverables.filter((deliverable) => deliverable.status === 'superseded').map((deliverable) => <DeliverableVersionCard key={deliverable.id} deliverable={deliverable} sessionId={data.session.id} timeZone={data.timeZone} />)}</details> : null}{group.archived.length > 0 ? <details className="card form-stack"><summary className="touch-target"><strong>Show archived versions</strong></summary>{group.archived.map((deliverable) => <DeliverableVersionCard key={deliverable.id} deliverable={deliverable} sessionId={data.session.id} timeZone={data.timeZone} />)}</details> : null}</section>)}</section></div>
}

function DeliverableVersionCard({ deliverable, sessionId, timeZone, current = false, shareTokens = [] }: { deliverable: EvidenceDeliverable; sessionId: string; timeZone: string | null; current?: boolean; shareTokens?: Awaited<ReturnType<typeof getDeliverablesData>>['shareTokens'] }) {
  return <article className="card form-stack"><div className="section-header"><div><h4>{formatDeliverableTitle(deliverable.title)} — Version {deliverable.version_number}</h4><p className="muted">{current ? 'Current final version · ' : ''}{getDeliverableSourceSummary(deliverable)}</p></div><span className="status-pill">{formatDeliverableStatus(deliverable.status)}</span></div><div className="metadata-list"><div><dt>Generated</dt><dd>{formatDateTime(deliverable.generated_at, timeZone)}</dd></div>{deliverable.finalized_at ? <div><dt>Finalized</dt><dd>{formatDateTime(deliverable.finalized_at, timeZone)}</dd></div> : null}<div><dt>Preview</dt><dd>{summarizeDeliverableContent(deliverable.content)}</dd></div></div><div className="button-row"><Link href={`/dashboard/sessions/${sessionId}/deliverables/${deliverable.id}`} className="button button-secondary touch-target">View</Link><Link href={`/dashboard/sessions/${sessionId}/deliverables/${deliverable.id}/print`} className="button button-secondary touch-target">Print</Link>{deliverable.status === 'draft' ? <form action={finalizeEvidenceDeliverableFormAction.bind(null, sessionId, deliverable.id)}><button className="button button-primary touch-target" type="submit">Finalize</button></form> : null}{deliverable.status === 'draft' ? <form action={archiveEvidenceDeliverableFormAction.bind(null, sessionId, deliverable.id)}><button className="button button-secondary touch-target" type="submit">Archive</button></form> : null}{deliverable.status === 'archived' ? <form action={restoreArchivedDeliverableFormAction.bind(null, sessionId, deliverable.id)}><button className="button button-secondary touch-target" type="submit">Restore draft</button></form> : null}</div>{current ? <DeliverableSharing sessionId={sessionId} deliverable={deliverable} shareTokens={shareTokens} timeZone={timeZone} compact /> : null}<DeliverablePreview deliverable={deliverable} /></article>
}

function sortDeliverables(deliverables: EvidenceDeliverable[]) {
  return [...deliverables].sort((a, b) => {
    const priority = (status: string) => status === 'final' ? 0 : status === 'draft' ? 1 : status === 'superseded' ? 2 : 3
    const priorityDiff = priority(a.status) - priority(b.status)
    if (priorityDiff !== 0) return priorityDiff
    return b.version_number - a.version_number
  })
}
