import Link from 'next/link'
import { formatDateTime } from '@/features/sessions'
import type { EvidenceImportBatch, EvidenceImportCaptureItem } from '../data'
import { EvidenceImportBulkActions } from './EvidenceImportBulkActions'
import { EvidenceImportReviewItem } from './EvidenceImportReviewItem'
import { EvidenceImportReviewProgress } from './EvidenceImportReviewProgress'
import { EvidenceImportSuggestionPanel } from './EvidenceImportSuggestionPanel'

export function EvidenceImportBatchReview({ sessionId, batch, captureItems, timeZone }: { sessionId: string; batch: EvidenceImportBatch; captureItems: EvidenceImportCaptureItem[]; timeZone: string | null }) {
  return <div className="form-stack"><section className="card detail-card form-stack"><div className="section-header"><div><p className="eyebrow">Import batch review</p><h2>{batch.source_kind} · {batch.status}</h2></div><div className="button-row"><Link className="button button-secondary" href={`/dashboard/sessions/${sessionId}/evidence`}>Evidence Library</Link><Link className="button button-secondary" href={`/dashboard/sessions/${sessionId}/suggestions`}>Suggestions</Link><Link className="button button-secondary" href={`/dashboard/sessions/${sessionId}/relationships`}>Relationship Explorer</Link><Link className="button button-secondary" href={`/dashboard/sessions/${sessionId}/deliverables`}>Deliverables</Link></div></div><dl className="metadata-list"><div><dt>Batch source kind</dt><dd>{batch.source_kind}</dd></div><div><dt>Status</dt><dd>{batch.status}</dd></div><div><dt>File count</dt><dd>{batch.file_count}</dd></div><div><dt>Processed count</dt><dd>{batch.processed_count}</dd></div><div><dt>Failed count</dt><dd>{batch.failed_count}</dd></div><div><dt>Created date</dt><dd>{formatDateTime(batch.created_at, timeZone)}</dd></div></dl></section><EvidenceImportReviewProgress captureItems={captureItems} /><EvidenceImportSuggestionPanel sessionId={sessionId} batchId={batch.id} captureItems={captureItems} /><EvidenceImportBulkActions sessionId={sessionId} batchId={batch.id} captureItems={captureItems} /><section className="form-stack"><h2>Imported item review list</h2>{captureItems.length === 0 ? <p className="muted">No evidence rows were created for this batch.</p> : captureItems.map((item) => <EvidenceImportReviewItem key={item.id} sessionId={sessionId} batchId={batch.id} item={item} />)}</section></div>
}
