import { EVENT_DATE_PRECISIONS, EVIDENCE_ASSERTION_TYPES, EVIDENCE_ENTITY_TYPES, EVIDENCE_OBJECT_TYPES, EVIDENCE_RELATIONSHIP_TYPES, SUGGESTION_REVIEW_STATUSES } from '@/features/evidence/constants'

export type SuggestionCategory = 'timeline' | 'entity' | 'observation' | 'relationship'
export type SuggestionDecision = 'accepted' | 'edited' | 'rejected'
export const AI_SUGGESTION_PROMPT_REQUIREMENTS = `Only extract observable facts, names, organizations, dates, and relationships. Never determine liability, fault, diagnosis, compliance outcome, legal conclusions, or financial recommendations. Always provide the corresponding source item IDs in source_evidence_ids, confidence, and a reasoning summary.`
export function parseSuggestionDecision(value: FormDataEntryValue | null): SuggestionDecision { const decision = String(value ?? '').trim(); if (decision === 'accepted' || decision === 'edited' || decision === 'rejected') return decision; throw new Error('Invalid suggestion decision') }
export function parseSuggestionCategory(value: FormDataEntryValue | null): SuggestionCategory { const category = String(value ?? '').trim(); if (category === 'timeline' || category === 'entity' || category === 'observation' || category === 'relationship') return category; throw new Error('Invalid suggestion category') }
export function assertAiSuggestionDefaults(values: { suggestion_source?: string; source_kind?: string; review_status?: string }) { if (values.review_status !== 'suggested') throw new Error('AI suggestions must default to suggested'); if (values.suggestion_source && values.suggestion_source !== 'ai') throw new Error('AI suggestions must be marked as AI sourced'); if (values.source_kind && values.source_kind !== 'ai') throw new Error('AI timeline suggestions must use AI source kind') }
export function parseEditedSuggestion(category: SuggestionCategory, formData: FormData) {
  if (category === 'timeline') { const title = String(formData.get('title') ?? '').trim(); if (!title) throw new Error('Timeline suggestion title is required'); const precision = String(formData.get('event_date_precision') ?? 'unknown'); return { title, description: String(formData.get('description') ?? '').trim() || null, event_start_at: String(formData.get('event_start_at') ?? '').trim() || null, event_date_precision: EVENT_DATE_PRECISIONS.includes(precision as never) ? precision : 'unknown' } }
  if (category === 'entity') { const displayName = String(formData.get('display_name') ?? '').trim(); if (!displayName) throw new Error('Entity suggestion name is required'); const entityType = String(formData.get('entity_type') ?? 'other'); return { display_name: displayName, normalized_name: displayName.toLocaleLowerCase(), entity_type: EVIDENCE_ENTITY_TYPES.includes(entityType as never) ? entityType : 'other', description: String(formData.get('description') ?? '').trim() || null } }
  if (category === 'observation') { const statement = String(formData.get('statement') ?? '').trim(); if (!statement) throw new Error('Observation suggestion statement is required'); const assertionType = String(formData.get('assertion_type') ?? 'factual_observation'); return { statement, normalized_statement: statement.toLocaleLowerCase(), assertion_type: EVIDENCE_ASSERTION_TYPES.includes(assertionType as never) ? assertionType : 'factual_observation' } }
  const sourceType = String(formData.get('source_type') ?? '').trim(); const targetType = String(formData.get('target_type') ?? '').trim(); const relationshipType = String(formData.get('relationship_type') ?? '').trim(); if (!EVIDENCE_OBJECT_TYPES.includes(sourceType as never) || !EVIDENCE_OBJECT_TYPES.includes(targetType as never) || !EVIDENCE_RELATIONSHIP_TYPES.includes(relationshipType as never)) throw new Error('Invalid relationship suggestion'); return { source_type: sourceType, target_type: targetType, relationship_type: relationshipType, relationship_label: String(formData.get('relationship_label') ?? '').trim() || null }
}
export function isSuggestionStatus(value: string) { return SUGGESTION_REVIEW_STATUSES.includes(value as never) }
