import Link from 'next/link'
import { bulkReviewEvidence, bulkReviewSuggestions, quickReviewEvidence, quickReviewSuggestion } from '@/features/evidence/review/actions'
import type { ReviewQueueData } from '@/features/evidence/review/data'

const kinds = [['all', 'All'], ['evidence', 'Evidence'], ['entities', 'Entities'], ['assertions', 'Assertions'], ['timeline', 'Timeline'], ['relationships', 'Relationships']] as const
const statuses = [['pending', 'All Pending'], ['unreviewed', 'Unreviewed'], ['needs_followup', 'Needs Follow-up'], ['suggested', 'Suggested']] as const
const sorts = [['newest', 'Newest first'], ['oldest', 'Oldest first'], ['capture_date', 'Capture date'], ['event_date', 'Event date']] as const

export function ReviewQueueWorkspace({ data }: { data: ReviewQueueData }) {
  const total = data.counts.unreviewedEvidence + data.counts.evidenceNeedsFollowup + data.counts.suggestedEntities + data.counts.suggestedAssertions + data.counts.suggestedTimelineEvents + data.counts.suggestedRelationships
  const reviewedEstimate = Math.max(0, data.allEvidenceCount - data.counts.unreviewedEvidence - data.counts.evidenceNeedsFollowup)
  const progressTotal = reviewedEstimate + total
  const percent = progressTotal ? Math.round((reviewedEstimate / progressTotal) * 100) : 100
  const next = data.items[0]
  return <section className="form-stack">
    <div className="metadata-list">
      <Metric label="Unreviewed Evidence" value={data.counts.unreviewedEvidence} /><Metric label="Evidence Needs Follow-up" value={data.counts.evidenceNeedsFollowup} /><Metric label="Suggested Entities" value={data.counts.suggestedEntities} /><Metric label="Suggested Assertions" value={data.counts.suggestedAssertions} /><Metric label="Suggested Timeline Events" value={data.counts.suggestedTimelineEvents} /><Metric label="Suggested Relationships" value={data.counts.suggestedRelationships} />
    </div>
    <div className="card detail-card form-stack"><div className="section-header"><div><p className="eyebrow">Review Progress</p><h2>{reviewedEstimate} reviewed of {progressTotal}</h2><p className="muted">{percent}% · Estimated remaining items: {total}</p></div>{next ? <a className="button button-primary touch-target" href={`#review-${next.kind}-${next.id}`}>Review Next</a> : <span className="button button-secondary">Queue clear</span>}</div></div>
    <form className="card detail-card form-grid" action={`/dashboard/sessions/${data.session.id}/evidence/review`}><label>Filter type<select name="kind" defaultValue={data.filters.kind}>{kinds.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Status<select name="status" defaultValue={data.filters.status}>{statuses.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Sort<select name="sort" defaultValue={data.filters.sort}>{sorts.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><button className="button button-secondary touch-target">Apply filters</button></form>
    <BulkForms sessionId={data.session.id} items={data.items} />
    <div className="form-stack">{data.items.length ? data.items.map((item) => <QueueCard key={`${item.kind}-${item.id}`} sessionId={data.session.id} item={item} />) : <div className="card detail-card"><h2>No pending review items</h2><p className="muted">Accepted, rejected, reviewed, excluded, and deleted records are hidden by default.</p></div>}</div>
  </section>
}
function Metric({ label, value }: { label: string; value: number }) { return <div><dt>{label}</dt><dd>{value}</dd></div> }
function BulkForms({ sessionId, items }: { sessionId: string; items: ReviewQueueData['items'] }) {
  const evidence = items.filter((item) => item.kind === 'evidence')
  const suggestions = (kind: string) => items.filter((item) => item.kind === kind)
  return <div className="card detail-card form-stack"><h2>Bulk Review</h2><p className="muted">Select records in the queue, then apply an action. Mutations are scoped to this session and organization.</p><form action={bulkReviewEvidence.bind(null, sessionId)} className="form-actions"><SelectionInputs items={evidence} /><button name="bulk_action" value="mark_reviewed" className="button button-secondary">Mark selected reviewed</button><button name="bulk_action" value="mark_followup" className="button button-secondary">Mark selected follow-up</button><button name="bulk_action" value="include" className="button button-secondary">Include selected</button><button name="bulk_action" value="exclude" className="button button-secondary">Exclude selected</button></form>{(['entity', 'observation', 'timeline', 'relationship'] as const).map((category) => <form key={category} action={bulkReviewSuggestions.bind(null, sessionId)} className="form-actions"><input type="hidden" name="category" value={category} /><SelectionInputs items={suggestions(category === 'entity' ? 'entities' : category === 'observation' ? 'assertions' : category === 'relationship' ? 'relationships' : 'timeline')} /><button name="decision" value="accepted" className="button button-secondary">Accept selected {category}</button><button name="decision" value="rejected" className="button button-secondary">Reject selected {category}</button></form>)}</div>
}
function SelectionInputs({ items }: { items: ReviewQueueData['items'] }) { return <fieldset className="form-stack"><legend className="eyebrow">Select records</legend>{items.length ? items.map((item) => <label key={item.id} className="secondary-link"><input type="checkbox" name="selected" value={item.id} /> {item.kind} · {item.id.slice(0, 8)}</label>) : <span className="muted">No matching records in the current queue.</span>}</fieldset> }
function QueueCard({ sessionId, item }: { sessionId: string; item: ReviewQueueData['items'][number] }) {
  const record = item.record as Record<string, unknown>
  const title = String(record.title ?? record.display_name ?? record.statement ?? record.relationship_label ?? record.filename ?? 'Untitled review item')
  return <article id={`review-${item.kind}-${item.id}`} className="card detail-card form-stack"><div className="section-header"><div><p className="eyebrow">{item.kind} · pending human review</p><h3>{title}</h3><p className="muted">Created {String(record.created_at ?? '')}</p></div><label className="secondary-link"><input type="checkbox" name="selected-visible" value={item.id} /> Select</label></div><p className="muted">{String(record.description ?? record.summary ?? record.notes ?? record.relationship_type ?? 'Source evidence provenance is retained on the record.')}</p>{item.kind === 'evidence' ? <EvidenceActions sessionId={sessionId} id={item.id} /> : <SuggestionActions sessionId={sessionId} id={item.id} kind={item.kind} />}</article>
}
function EvidenceActions({ sessionId, id }: { sessionId: string; id: string }) { const action = quickReviewEvidence.bind(null, sessionId, id); return <div className="form-actions"><form action={action}><input type="hidden" name="evidence_review_status" value="reviewed" /><button className="button button-primary">Accept</button></form><form action={action}><input type="hidden" name="evidence_review_status" value="needs_followup" /><button className="button button-secondary">Needs Follow-up</button></form><form action={action}><input type="hidden" name="evidence_review_status" value="excluded" /><input type="hidden" name="include_in_report" value="false" /><button className="button button-secondary">Exclude from Outputs</button></form></div> }
function SuggestionActions({ sessionId, id, kind }: { sessionId: string; id: string; kind: string }) { const category = kind === 'entities' ? 'entity' : kind === 'assertions' ? 'observation' : kind === 'relationships' ? 'relationship' : 'timeline'; const action = quickReviewSuggestion.bind(null, sessionId, id); return <div className="form-actions"><form action={action}><input type="hidden" name="category" value={category} /><input type="hidden" name="decision" value="accepted" /><button className="button button-primary">Accept</button></form><form action={action}><input type="hidden" name="category" value={category} /><input type="hidden" name="decision" value="rejected" /><button className="button button-secondary">Reject</button></form></div> }
