/* eslint-disable @typescript-eslint/no-explicit-any */
import type { WorkspaceBrandProfile } from "@/features/branding/types";
const areas = ["cover_page","header","section_headings","body_text","evidence_titles","evidence_notes","footer","signature"];
export function ReportStudioHiddenFields({ brand, selectedSessionId, selectedTemplateId }: { brand: WorkspaceBrandProfile; selectedSessionId: string | null; selectedTemplateId?: string | null }) {
  const rs = brand.report_style;
  const bools: Record<string, boolean | undefined> = {
    evidence_numbering: rs.evidenceNumbering, evidence_appendix: rs.evidenceAppendix, timestamps: rs.timestamps, capture_metadata: rs.captureMetadata, evidence_notes: rs.notes, evidence_location: rs.location, evidence_ids: rs.evidenceIds, section_grouping: rs.sectionGrouping, show_report_date: rs.showReportDate, show_prepared_by: rs.showPreparedBy, show_page_number: rs.showPageNumber, show_generated_by_cred: rs.showGeneratedByCred, showCoverLogo: rs.showCoverLogo, showCoverCompanyInfo: rs.showCoverCompanyInfo, showCoverTitle: rs.showCoverTitle, showCoverClient: rs.showCoverClient, showCoverAsset: rs.showCoverAsset, showCoverLocation: rs.showCoverLocation, showCoverPreparedBy: rs.showCoverPreparedBy, showCoverDate: rs.showCoverDate, showCoverReportId: rs.showCoverReportId, showCoverImage: rs.showCoverImage, showConfidentialityLabel: rs.showConfidentialityLabel, showSectionLabels: rs.showSectionLabels, showSectionDividers: rs.showSectionDividers, showSectionNumbers: rs.showSectionNumbers, signature_date: rs.signatureDate, approval_block: rs.approvalBlock, header_gradient_preset: rs.headerOptions?.gradientPreset, show_report_id: brand.show_report_id, show_page_date: brand.show_page_date, show_contact_info: brand.show_contact_info, show_confidentiality_note: brand.show_confidentiality_note, show_signature_block: brand.show_signature_block,
  };
  return <>
    <input type="hidden" name="selected_session_output_id" value={selectedSessionId ?? ""} />
    <input type="hidden" name="selected_template_id" value={selectedTemplateId ?? ""} />
    {(["display_name","tagline","phone","email","website","address","license_number","certification_number","tax_number","insurance_number","business_hours","department","prepared_by_name","prepared_by_title","footer_text"] as const).map((k)=><input key={k} type="hidden" name={k} value={(brand[k] as string | null) ?? ""} />)}
    {(["logo","dark_logo","icon","signature"] as const).map((k)=><input key={k} type="hidden" name={`current_${k}`} value={(k==="logo"?brand.logo_storage_path:k==="dark_logo"?brand.dark_logo_storage_path:k==="icon"?brand.icon_storage_path:brand.signature_storage_path) ?? ""} />)}
    {Object.entries(brand.colors).map(([k,v])=><input key={k} type="hidden" name={`color_${k}`} value={v} />)}
    <input type="hidden" name="typography_preset" value={brand.typography.preset} /><input type="hidden" name="typography_headingStack" value={brand.typography.headingStack} /><input type="hidden" name="typography_bodyStack" value={brand.typography.bodyStack} /><input type="hidden" name="typography_labelStyle" value={brand.typography.labelStyle} /><input type="hidden" name="typography_headingWeight" value={brand.typography.headingWeight} /><input type="hidden" name="typography_titleWeight" value={brand.typography.titleWeight} /><input type="hidden" name="typography_letterSpacing" value={brand.typography.letterSpacing} /><input type="hidden" name="typography_titleSpacing" value={brand.typography.titleSpacing} /><input type="hidden" name="typography_sectionHeadingLetterSpacing" value={brand.typography.sectionHeadingLetterSpacing} /><input type="hidden" name="typography_metadataStyle" value={brand.typography.metadataStyle} />
    {areas.map((a)=><input key={a} type="hidden" name={`typography_area_${a}`} value={(brand.typography as any).areaStacks?.[a] ?? brand.typography.bodyStack} />)}
    <input type="hidden" name="cover_background_color" value={rs.coverBackgroundColor} /><input type="hidden" name="cover_gradient_start" value={rs.coverGradientStart} /><input type="hidden" name="cover_gradient_end" value={rs.coverGradientEnd} /><input type="hidden" name="cover_accent_color" value={rs.coverAccentColor} /><input type="hidden" name="cover_text_color" value={rs.coverTextColor} /><input type="hidden" name="cover_title_alignment" value={rs.coverTitleAlignment} /><input type="hidden" name="cover_logo_size" value={rs.coverLogoSize} /><input type="hidden" name="header_layout" value={brand.header_layout} /><input type="hidden" name="footer_layout" value={String(brand.footer_layout)} /><input type="hidden" name="section_style" value={rs.sectionStyle} /><input type="hidden" name="section_spacing" value={rs.sectionSpacing} /><input type="hidden" name="evidence_image_size" value={rs.evidenceImageSize} /><input type="hidden" name="evidence_style" value={rs.evidenceStyle} /><input type="hidden" name="cover_page" value={rs.coverPage} /><input type="hidden" name="cover_image_source" value={rs.coverImageSource} /><input type="hidden" name="signature_layout" value={rs.signatureLayout} /><input type="hidden" name="watermark_option" value={rs.watermark.option} /><input type="hidden" name="watermark_text" value={rs.watermark.text} /><input type="hidden" name="typed_signature" value={rs.typedSignature ?? ""} /><input type="hidden" name="reviewed_by_label" value={rs.reviewedByLabel} />
    {Object.entries(bools).map(([k,v])=><input key={k} type="hidden" name={k} value={v ? "on" : ""} />)}
  </>;
}
