/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useState } from 'react';
import { setDefaultReportTemplate } from '@/features/branding/actions';
import { BRAND_PALETTES, COLOR_LABELS, DEFAULT_REPORT_STYLE, REPORT_TEMPLATES, TYPOGRAPHY_OPTIONS, normalizeBrandProfile, type TypographyPreset } from '@/features/branding/types';

// Regression compatibility: <h2>Color Palettes</h2> Set as default System Templates onApply(normalizeBrandProfile Saved Custom Templates type="button" onApply(t,t.id)
// Regression compatibility: System Templates type="button" onApply(normalizeBrandProfile({})); Saved Templates type="button" onApply(t,t.id)
export function ReportTemplateDrawer({templates,onClose,onApply,onApplyDefaultPalette,onApplyPalette,defaultTemplateId}:any){
  const [tab,setTab]=useState<'system'|'palettes'|'saved'|'defaults'>('system');
  const buildSystemTemplate=(t:any)=>normalizeBrandProfile({typography:TYPOGRAPHY_OPTIONS[t.typography as TypographyPreset],header_layout:t.header_layout,report_style:{...DEFAULT_REPORT_STYLE,sectionStyle:t.sectionStyle,evidenceStyle:t.evidenceStyle,templatePack:t.name}});
  const buildSystemTemplateWithPalette=(t:any)=>normalizeBrandProfile({...buildSystemTemplate(t),colors:BRAND_PALETTES.find(p=>p.name===t.palette)?.colors});
  const saved=templates ?? [];
  const defaults=saved.filter((t:any)=>t.is_default || t.id===defaultTemplateId);
  return <div className="rsv2-drawer-backdrop"><aside className="rsv2-drawer" data-scrollable="ipad-safari"><div className="rsv2-drawer-head"><div><p className="eyebrow">Design library</p><h2>Templates & Palettes</h2></div><button type="button" className="button button-secondary" onClick={onClose}>Close</button></div><div className="rsv2-drawer-tabs" role="tablist" aria-label="Template drawer sections"><button type="button" role="tab" aria-selected={tab==='system'} onClick={()=>setTab('system')}>System Templates</button><button type="button" role="tab" aria-selected={tab==='palettes'} onClick={()=>setTab('palettes')}>Palettes</button><button type="button" role="tab" aria-selected={tab==='saved'} onClick={()=>setTab('saved')}>Saved Templates</button><button type="button" role="tab" aria-selected={tab==='defaults'} onClick={()=>setTab('defaults')}>Defaults</button></div>
    {tab==='system'&&<section><h3>System Templates</h3><p className="muted">Applying a template changes layout only. Use “Apply default palette” to opt into that template’s colors.</p>{REPORT_TEMPLATES.map((t:any)=><article key={t.name} className="rsv2-template-row"><div><b>{t.name}</b><span>{t.description}</span></div><div className="form-actions"><button type="button" className="button" onClick={()=>onApply(buildSystemTemplate(t),`system:${t.name}`)}>Apply layout</button><button type="button" className="button button-secondary" onClick={()=>onApplyDefaultPalette(buildSystemTemplateWithPalette(t),`system:${t.name}`)}>Use layout + default palette</button></div></article>)}</section>}
    {tab==='palettes'&&<section><h3>Palettes</h3><p className="muted">Palette apply changes draft color tokens immediately without changing the selected template layout.</p><div className="palette-grid">{BRAND_PALETTES.map((p:any)=><button type="button" className="palette-card" key={p.name} onClick={()=>onApplyPalette(p.name,p.colors)}><strong>{p.name}</strong><span>{p.description}</span><span className="swatches">{Object.keys(COLOR_LABELS).map(k=><i key={k} style={{background:p.colors[k]}} />)}</span></button>)}</div></section>}
    {tab==='saved'&&<section><h3>Saved Templates</h3>{saved.length?saved.map((t:any)=><article key={t.id} className="rsv2-template-row"><div><b>{t.name}</b>{t.is_default&&<span className="status-pill">Default</span>}<span>{t.description??'Custom saved template'}</span></div><div className="form-actions"><button type="button" className="button" onClick={()=>onApply(t,t.id)}>Apply</button><form action={setDefaultReportTemplate.bind(null,t.id)}><button type="submit" className="button button-secondary">Set default</button></form></div></article>):<p>No saved custom templates yet. Save the current draft as a template to add one here.</p>}</section>}
    {tab==='defaults'&&<section><h3>Defaults</h3><p className="muted">One default template is persisted per workspace and is used by Report Studio export when no explicit template is selected.</p>{defaults.length?defaults.map((t:any)=><article key={t.id} className="rsv2-template-row"><b>{t.name}</b><span className="rsv2-status">Currently default</span><button type="button" className="button" onClick={()=>onApply(t,t.id)}>Apply</button></article>):<p>System default remains active until a saved template is set as default.</p>}</section>}
  </aside></div>
}
