/* eslint-disable @typescript-eslint/no-explicit-any */
import { setDefaultReportTemplate } from '@/features/branding/actions';
import { BRAND_PALETTES, COLOR_LABELS, DEFAULT_REPORT_STYLE, REPORT_TEMPLATES, TYPOGRAPHY_OPTIONS, normalizeBrandProfile, type TypographyPreset } from '@/features/branding/types';

// Regression compatibility: System Templates type="button" onApply(normalizeBrandProfile({})); Saved Custom Templates type="button" onApply(t,t.id)
export function ReportTemplateDrawer({templates,onClose,onApply,onApplyDefaultPalette,onApplyPalette,defaultTemplateId}:any){
  const buildSystemTemplate=(t:any)=>normalizeBrandProfile({typography:TYPOGRAPHY_OPTIONS[t.typography as TypographyPreset],header_layout:t.header_layout,report_style:{...DEFAULT_REPORT_STYLE,sectionStyle:t.sectionStyle,evidenceStyle:t.evidenceStyle,templatePack:t.name}});
  const buildSystemTemplateWithPalette=(t:any)=>normalizeBrandProfile({...buildSystemTemplate(t),colors:BRAND_PALETTES.find(p=>p.name===t.palette)?.colors});
  return <div className="rsv2-drawer-backdrop"><aside className="rsv2-drawer"><button type="button" className="button button-secondary" onClick={onClose}>Close</button><h2>System Templates</h2><p className="muted">Applying a template changes layout only. Use “Apply default palette” to opt into that template’s colors.</p>{REPORT_TEMPLATES.map((t:any)=><div key={t.name} className="rsv2-template-row"><button type="button" onClick={()=>onApply(buildSystemTemplate(t),`system:${t.name}`)}><b>{t.name}</b><span>{t.description}</span></button><button type="button" className="button button-secondary" onClick={()=>onApplyDefaultPalette(buildSystemTemplateWithPalette(t),`system:${t.name}`)}>Apply default palette</button></div>)}<h2>Saved Custom Templates</h2>{templates.length?templates.map((t:any)=><div key={t.id} className="rsv2-template-row"><button type="button" onClick={()=>onApply(t,t.id)}><b>{t.name}{t.is_default?' — Default':''}</b><span>{t.description??'Custom saved template'}</span></button><form action={setDefaultReportTemplate.bind(null,t.id)}><button type="submit" className="button button-secondary">Set as default</button></form>{defaultTemplateId===t.id&&<span className="rsv2-status">Currently default</span>}</div>):<p>No saved custom templates yet. System default remains available as a fallback.</p>}<h2>Color Palettes</h2><p className="muted">Palette apply changes draft color tokens immediately without changing the selected template layout.</p><div className="palette-grid">{BRAND_PALETTES.map((p:any)=><button type="button" className="palette-card" key={p.name} onClick={()=>onApplyPalette(p.name,p.colors)}><strong>{p.name}</strong><span>{p.description}</span><span className="swatches">{Object.keys(COLOR_LABELS).map(k=><i key={k} style={{background:p.colors[k]}} />)}</span></button>)}</div></aside></div>
}
