alter table public.documentation_sessions
  add column if not exists deleted_at timestamptz,
  add column if not exists display_id text;

comment on column public.documentation_sessions.deleted_at is
  'Soft-delete timestamp for hiding sessions without deleting evidence or storage files.';
comment on column public.documentation_sessions.display_id is
  'Stable human-friendly organization-scoped session identifier generated by the application, e.g. EV-2026-A7K3.';

create unique index if not exists documentation_sessions_org_display_id_unique_idx
  on public.documentation_sessions (organization_id, display_id)
  where display_id is not null;

create index if not exists documentation_sessions_org_deleted_archived_updated_idx
  on public.documentation_sessions (organization_id, deleted_at, archived_at, updated_at desc);
