export const HEX_COLOR_PATTERN = /^#[0-9A-Fa-f]{6}$/
export const HEADER_LAYOUTS = ['classic_letterhead','compact_service','bold_banner','split_identity','minimal','report_cover','left_rail','certification_block'] as const
export const TYPOGRAPHY_PRESETS = ['professional_sans','modern_compact','editorial_serif','technical_report','field_service','legal_document','clean_corporate','utility_mono_accent'] as const
export const EVIDENCE_IMAGE_SIZES = ['compact','standard','large','full_width'] as const
export const EVIDENCE_STYLES = ['carded','clean_list','numbered_appendix','photo_grid'] as const
export const SECTION_STYLES = ['carded','clean','ruled','binder','executive'] as const
export type HeaderLayout = typeof HEADER_LAYOUTS[number]
export type TypographyPreset = typeof TYPOGRAPHY_PRESETS[number]
export type EvidenceImageSize = typeof EVIDENCE_IMAGE_SIZES[number]
export type EvidenceStyle = typeof EVIDENCE_STYLES[number]
export type SectionStyle = typeof SECTION_STYLES[number]
export type BrandColors = { primary:string; accent:string; headerBackground:string; headerText:string; footerBackground:string; footerText:string; sectionHeading:string; border:string }
export type TypographySettings = { preset:TypographyPreset; headingStack:string; bodyStack:string; labelStyle:'uppercase'|'title'|'sentence'|'mono'; titleWeight:number; titleSpacing:string; sectionHeadingLetterSpacing:string }
export type ReportStyle = { sectionStyle:SectionStyle; evidenceImageSize:EvidenceImageSize; evidenceStyle:EvidenceStyle; evidenceNumbering:boolean; evidenceAppendix:boolean; timestamps:boolean; captureMetadata:boolean; notes:boolean; location:boolean; evidenceIds:boolean; sectionGrouping:boolean; showReportDate:boolean; showPreparedBy:boolean; showPageNumber:boolean; showGeneratedByCred:boolean; typedSignature:string|null; signatureDate:boolean; approvalBlock:boolean; reviewedByLabel:string }
export type WorkspaceBrandProfile = { id?:string; organization_id?:string; display_name:string|null; tagline:string|null; phone:string|null; email:string|null; website:string|null; address:string|null; prepared_by_name:string|null; prepared_by_title:string|null; logo_storage_path:string|null; dark_logo_storage_path:string|null; icon_storage_path:string|null; signature_storage_path:string|null; colors:BrandColors; typography:TypographySettings; header_layout:HeaderLayout; footer_layout:string; report_style:ReportStyle; footer_text:string|null; show_report_id:boolean; show_page_date:boolean; show_contact_info:boolean; show_confidentiality_note:boolean; show_signature_block:boolean }
export const DEFAULT_BRAND_COLORS: BrandColors = { primary:'#155dfc', accent:'#13213a', headerBackground:'#ffffff', headerText:'#18243a', footerBackground:'#ffffff', footerText:'#62728a', sectionHeading:'#18243a', border:'#d9e2ee' }
export const COLOR_LABELS: Record<keyof BrandColors,string> = { primary:'Primary', accent:'Accent', headerBackground:'Header background', headerText:'Header text', footerBackground:'Footer background', footerText:'Footer text', sectionHeading:'Section heading', border:'Border' }
export const BRAND_PALETTES: Array<{name:string; description:string; colors:BrandColors}> = [
  {name:'CRED Blue',description:'Default trusted service documentation.',colors:DEFAULT_BRAND_COLORS},
  {name:'Slate Professional',description:'Calm B2B report tone.',colors:{primary:'#334155',accent:'#0f172a',headerBackground:'#f8fafc',headerText:'#0f172a',footerBackground:'#f1f5f9',footerText:'#475569',sectionHeading:'#1e293b',border:'#cbd5e1'}},
  {name:'Emerald Service',description:'Clean field service brand.',colors:{primary:'#059669',accent:'#064e3b',headerBackground:'#ecfdf5',headerText:'#064e3b',footerBackground:'#064e3b',footerText:'#d1fae5',sectionHeading:'#047857',border:'#a7f3d0'}},
  {name:'Copper Trade',description:'Warm construction and trade style.',colors:{primary:'#b45309',accent:'#451a03',headerBackground:'#fff7ed',headerText:'#431407',footerBackground:'#451a03',footerText:'#fed7aa',sectionHeading:'#92400e',border:'#fed7aa'}},
  {name:'Graphite Industrial',description:'Durable industrial documentation.',colors:{primary:'#3f3f46',accent:'#18181b',headerBackground:'#27272a',headerText:'#fafafa',footerBackground:'#18181b',footerText:'#d4d4d8',sectionHeading:'#27272a',border:'#a1a1aa'}},
  {name:'Safety Amber',description:'Safety-forward operations reports.',colors:{primary:'#d97706',accent:'#111827',headerBackground:'#fffbeb',headerText:'#111827',footerBackground:'#111827',footerText:'#fde68a',sectionHeading:'#b45309',border:'#fcd34d'}},
  {name:'Executive Navy',description:'Premium leadership package.',colors:{primary:'#1d4ed8',accent:'#0f172a',headerBackground:'#0f172a',headerText:'#eff6ff',footerBackground:'#0b1120',footerText:'#bfdbfe',sectionHeading:'#1e3a8a',border:'#bfdbfe'}},
  {name:'Clean Medical',description:'Bright clinical presentation.',colors:{primary:'#0891b2',accent:'#155e75',headerBackground:'#ecfeff',headerText:'#164e63',footerBackground:'#f0fdfa',footerText:'#0f766e',sectionHeading:'#0e7490',border:'#a5f3fc'}},
  {name:'Legal Classic',description:'Formal evidence packet.',colors:{primary:'#374151',accent:'#111827',headerBackground:'#ffffff',headerText:'#111827',footerBackground:'#f9fafb',footerText:'#4b5563',sectionHeading:'#111827',border:'#9ca3af'}},
  {name:'Property Inspection',description:'Real estate condition report.',colors:{primary:'#2563eb',accent:'#365314',headerBackground:'#f8fafc',headerText:'#1e293b',footerBackground:'#ecfccb',footerText:'#365314',sectionHeading:'#1d4ed8',border:'#bbf7d0'}},
  {name:'Fleet Utility',description:'Vehicle and equipment service.',colors:{primary:'#0f766e',accent:'#1f2937',headerBackground:'#f9fafb',headerText:'#1f2937',footerBackground:'#1f2937',footerText:'#ccfbf1',sectionHeading:'#0f766e',border:'#99f6e4'}},
  {name:'Modern Black',description:'High-end monochrome brand.',colors:{primary:'#000000',accent:'#525252',headerBackground:'#000000',headerText:'#ffffff',footerBackground:'#000000',footerText:'#e5e5e5',sectionHeading:'#111111',border:'#d4d4d4'}},
  {name:'Soft Neutral',description:'Warm approachable paperwork.',colors:{primary:'#78716c',accent:'#44403c',headerBackground:'#fafaf9',headerText:'#44403c',footerBackground:'#f5f5f4',footerText:'#57534e',sectionHeading:'#57534e',border:'#d6d3d1'}},
  {name:'High Contrast',description:'Maximum readability.',colors:{primary:'#1d4ed8',accent:'#000000',headerBackground:'#000000',headerText:'#ffffff',footerBackground:'#000000',footerText:'#ffffff',sectionHeading:'#000000',border:'#000000'}},
]
export const TYPOGRAPHY_OPTIONS: Record<TypographyPreset, TypographySettings & {name:string; description:string}> = {
  professional_sans:{name:'Professional Sans',description:'Balanced system UI style.',preset:'professional_sans',headingStack:'Inter, Arial, Helvetica, sans-serif',bodyStack:'Inter, Arial, Helvetica, sans-serif',labelStyle:'uppercase',titleWeight:800,titleSpacing:'-0.03em',sectionHeadingLetterSpacing:'-0.01em'},
  modern_compact:{name:'Modern Compact',description:'Dense modern service reports.',preset:'modern_compact',headingStack:'Arial Narrow, Arial, sans-serif',bodyStack:'Arial, Helvetica, sans-serif',labelStyle:'uppercase',titleWeight:800,titleSpacing:'-0.045em',sectionHeadingLetterSpacing:'0'},
  editorial_serif:{name:'Editorial Serif',description:'Polished narrative documents.',preset:'editorial_serif',headingStack:'Georgia, Times New Roman, serif',bodyStack:'Arial, Helvetica, sans-serif',labelStyle:'title',titleWeight:700,titleSpacing:'-0.02em',sectionHeadingLetterSpacing:'0'},
  technical_report:{name:'Technical Report',description:'Precise diagnostic formatting.',preset:'technical_report',headingStack:'Arial, Helvetica, sans-serif',bodyStack:'Arial, Helvetica, sans-serif',labelStyle:'mono',titleWeight:800,titleSpacing:'-0.015em',sectionHeadingLetterSpacing:'0.08em'},
  field_service:{name:'Field Service',description:'Clear technician handoff.',preset:'field_service',headingStack:'Verdana, Geneva, sans-serif',bodyStack:'Verdana, Geneva, sans-serif',labelStyle:'uppercase',titleWeight:800,titleSpacing:'-0.02em',sectionHeadingLetterSpacing:'0.04em'},
  legal_document:{name:'Legal Document',description:'Formal serif headings.',preset:'legal_document',headingStack:'Georgia, Times New Roman, serif',bodyStack:'Times New Roman, Georgia, serif',labelStyle:'title',titleWeight:700,titleSpacing:'0',sectionHeadingLetterSpacing:'0.02em'},
  clean_corporate:{name:'Clean Corporate',description:'Executive-ready system stack.',preset:'clean_corporate',headingStack:'system-ui, -apple-system, Segoe UI, sans-serif',bodyStack:'system-ui, -apple-system, Segoe UI, sans-serif',labelStyle:'sentence',titleWeight:750,titleSpacing:'-0.035em',sectionHeadingLetterSpacing:'-0.01em'},
  utility_mono_accent:{name:'Utility Mono Accent',description:'Mono labels with readable body.',preset:'utility_mono_accent',headingStack:'Arial, Helvetica, sans-serif',bodyStack:'Arial, Helvetica, sans-serif',labelStyle:'mono',titleWeight:800,titleSpacing:'-0.025em',sectionHeadingLetterSpacing:'0.1em'},
}
export const REPORT_TEMPLATES = [
  {name:'Classic Letterhead',description:'Traditional business letterhead.',palette:'CRED Blue',typography:'professional_sans',header_layout:'classic_letterhead',sectionStyle:'carded',evidenceStyle:'carded'},
  {name:'Modern Service Report',description:'Clean service summary with cards.',palette:'Emerald Service',typography:'modern_compact',header_layout:'compact_service',sectionStyle:'carded',evidenceStyle:'photo_grid'},
  {name:'Bold Banner',description:'Strong branded title band.',palette:'Executive Navy',typography:'clean_corporate',header_layout:'bold_banner',sectionStyle:'executive',evidenceStyle:'carded'},
  {name:'Inspection Binder',description:'Binder-style condition package.',palette:'Property Inspection',typography:'field_service',header_layout:'left_rail',sectionStyle:'binder',evidenceStyle:'numbered_appendix'},
  {name:'Legal Evidence Package',description:'Formal defensible evidence packet.',palette:'Legal Classic',typography:'legal_document',header_layout:'certification_block',sectionStyle:'ruled',evidenceStyle:'numbered_appendix'},
  {name:'Technical Diagnostic Report',description:'Detailed diagnostic findings.',palette:'Graphite Industrial',typography:'technical_report',header_layout:'split_identity',sectionStyle:'ruled',evidenceStyle:'clean_list'},
  {name:'Property Condition Report',description:'Client-friendly property review.',palette:'Soft Neutral',typography:'clean_corporate',header_layout:'report_cover',sectionStyle:'carded',evidenceStyle:'photo_grid'},
  {name:'Fleet Service Report',description:'Utility-focused fleet packet.',palette:'Fleet Utility',typography:'field_service',header_layout:'compact_service',sectionStyle:'carded',evidenceStyle:'clean_list'},
  {name:'Minimal Clean',description:'Low-distraction professional report.',palette:'Modern Black',typography:'professional_sans',header_layout:'minimal',sectionStyle:'clean',evidenceStyle:'clean_list'},
  {name:'Executive Summary',description:'Leadership-ready overview.',palette:'Executive Navy',typography:'editorial_serif',header_layout:'bold_banner',sectionStyle:'executive',evidenceStyle:'carded'},
] as const
export const DEFAULT_REPORT_STYLE: ReportStyle = { sectionStyle:'carded', evidenceImageSize:'standard', evidenceStyle:'carded', evidenceNumbering:true, evidenceAppendix:true, timestamps:true, captureMetadata:false, notes:true, location:false, evidenceIds:true, sectionGrouping:true, showReportDate:true, showPreparedBy:true, showPageNumber:false, showGeneratedByCred:false, typedSignature:null, signatureDate:true, approvalBlock:false, reviewedByLabel:'Reviewed by' }
export const DEFAULT_BRAND_PROFILE: WorkspaceBrandProfile = { display_name:null, tagline:null, phone:null, email:null, website:null, address:null, prepared_by_name:null, prepared_by_title:null, logo_storage_path:null, dark_logo_storage_path:null, icon_storage_path:null, signature_storage_path:null, colors:DEFAULT_BRAND_COLORS, typography:TYPOGRAPHY_OPTIONS.professional_sans, header_layout:'classic_letterhead', footer_layout:'standard', report_style:DEFAULT_REPORT_STYLE, footer_text:null, show_report_id:true, show_page_date:true, show_contact_info:true, show_confidentiality_note:false, show_signature_block:true }
export function isValidHexColor(value:string){ return HEX_COLOR_PATTERN.test(value.trim()) }
export function normalizeBrandProfile(row: Partial<WorkspaceBrandProfile> | null | undefined): WorkspaceBrandProfile { const preset = TYPOGRAPHY_PRESETS.includes(row?.typography?.preset as TypographyPreset) ? row?.typography?.preset as TypographyPreset : 'professional_sans'; const rawHeader = row?.header_layout as string | undefined; const header = HEADER_LAYOUTS.includes(rawHeader as HeaderLayout) ? rawHeader as HeaderLayout : rawHeader === 'classic' ? 'classic_letterhead' : rawHeader === 'compact' ? 'compact_service' : rawHeader === 'bold' ? 'bold_banner' : rawHeader === 'split' ? 'split_identity' : rawHeader === 'minimal' ? 'minimal' : 'classic_letterhead'; return { ...DEFAULT_BRAND_PROFILE, ...row, colors:{...DEFAULT_BRAND_COLORS,...(row?.colors ?? {})}, typography:{...TYPOGRAPHY_OPTIONS[preset],...(row?.typography ?? {}),preset}, header_layout:header, report_style:{...DEFAULT_REPORT_STYLE,...(row?.report_style ?? {})} } }
