export const HEX_COLOR_PATTERN = /^#[0-9A-Fa-f]{6}$/
export const HEADER_LAYOUTS = ['classic_letterhead','compact_service','bold_banner','split_identity','minimal','report_cover','left_rail','certification_block','centered_logo','two_column_details','government_form_header','industrial_strip'] as const
export const COVER_PAGE_LAYOUTS = ['none','simple_cover','professional_cover'] as const
export const FOOTER_LAYOUTS = ['minimal','contact_footer','legal_footer','report_id_footer','split_footer','confidential_footer','signature_footer'] as const
export const WATERMARK_OPTIONS = ['none','draft','confidential','internal','copy','final','void','custom_text'] as const
export const SIGNATURE_LAYOUTS = ['single_signature','two_signatures','three_signatures','stacked_signatures','approval_panel'] as const
export const TYPOGRAPHY_PRESETS = ['professional_sans','modern_compact','editorial_serif','technical_report','field_service','legal_document','clean_corporate','utility_mono_accent','government_form','executive_letter','inspection_notes','industrial_label'] as const
export const EVIDENCE_IMAGE_SIZES = ['compact','standard','large','full_width'] as const
export const EVIDENCE_STYLES = ['compact_list','standard_cards','large_photo_cards','full_width_photos','two_column_photo_grid','numbered_appendix','clean_evidence_list','photo_left_notes_right','notes_first_photos_below','insurance_photo_grid','carded','clean_list','photo_grid'] as const
export const SECTION_STYLES = ['carded','clean_document','boxed','minimal','classic','industrial','corporate','legal','inspection','technical','clean','ruled','binder','executive'] as const
export type HeaderLayout = typeof HEADER_LAYOUTS[number]
export type CoverPageLayout = typeof COVER_PAGE_LAYOUTS[number]
export type FooterLayout = typeof FOOTER_LAYOUTS[number]
export type WatermarkOption = typeof WATERMARK_OPTIONS[number]
export type SignatureLayout = typeof SIGNATURE_LAYOUTS[number]
export type TypographyPreset = typeof TYPOGRAPHY_PRESETS[number]
export type EvidenceImageSize = typeof EVIDENCE_IMAGE_SIZES[number]
export type EvidenceStyle = typeof EVIDENCE_STYLES[number]
export type SectionStyle = typeof SECTION_STYLES[number]
export type BrandColors = { primary:string; accent:string; headerBackground:string; headerText:string; footerBackground:string; footerText:string; sectionHeading:string; border:string; mutedBackground:string; evidenceAccent:string }
export type TypographySettings = { preset:TypographyPreset; headingStack:string; bodyStack:string; labelStyle:'uppercase'|'title'|'sentence'|'mono'; headingWeight:number; titleWeight:number; letterSpacing:string; titleSpacing:string; sectionHeadingStyle:string; metadataStyle:string; sectionHeadingLetterSpacing:string }
export type SignatureBlock = { key:string; enabled:boolean; label:string; typedName:string|null; title:string|null; showDate:boolean; useSignatureImage:boolean; showSignatureLine:boolean }
export type CustomReportField = { id:string; label:string; showInHeader:boolean; showInCover:boolean; showInIdentityBlock:boolean; showInFooter:boolean }
export type ReportStyle = { templatePack:string; coverPage:CoverPageLayout; coverImageSource:'first_evidence_image'|'selected_report_image'|'none'; showCoverLogo:boolean; showCoverCompanyInfo:boolean; showCoverTitle:boolean; showCoverClient:boolean; showCoverAsset:boolean; showCoverLocation:boolean; showCoverPreparedBy:boolean; showCoverDate:boolean; showCoverReportId:boolean; showCoverImage:boolean; showConfidentialityLabel:boolean; sectionStyle:SectionStyle; showSectionLabels:boolean; showSectionDividers:boolean; showSectionNumbers:boolean; sectionSpacing:'compact'|'standard'|'spacious'; sectionTitleStyle:string; subsectionStyle:string; evidenceImageSize:EvidenceImageSize; evidenceStyle:EvidenceStyle; evidenceNumbering:boolean; evidenceAppendix:boolean; timestamps:boolean; captureMetadata:boolean; notes:boolean; location:boolean; fileNames:boolean; captions:boolean; pageBreaksBetweenEvidenceGroups:boolean; evidenceIds:boolean; sectionGrouping:boolean; showReportDate:boolean; showPreparedBy:boolean; showPageNumber:boolean; showGeneratedByCred:boolean; typedSignature:string|null; signatureDate:boolean; approvalBlock:boolean; reviewedByLabel:string; headerOptions:Record<string,boolean>; watermark:{ option:WatermarkOption; text:string; opacity:'subtle'|'standard'|'strong'; placement:'center'|'diagonal'|'footer_stamp'; draftOnly:boolean }; signatureLayout:SignatureLayout; signatureBlocks:SignatureBlock[]; customFields:CustomReportField[] }
export type WorkspaceBrandProfile = { id?:string; organization_id?:string; display_name:string|null; tagline:string|null; phone:string|null; email:string|null; website:string|null; address:string|null; license_number:string|null; certification_number:string|null; tax_number:string|null; insurance_number:string|null; business_hours:string|null; department:string|null; branch_location:string|null; prepared_by_name:string|null; prepared_by_title:string|null; logo_storage_path:string|null; dark_logo_storage_path:string|null; icon_storage_path:string|null; signature_storage_path:string|null; colors:BrandColors; typography:TypographySettings; header_layout:HeaderLayout; footer_layout:FooterLayout|string; report_style:ReportStyle; footer_text:string|null; show_report_id:boolean; show_page_date:boolean; show_contact_info:boolean; show_confidentiality_note:boolean; show_signature_block:boolean }
export const DEFAULT_BRAND_COLORS: BrandColors = { primary:'#155dfc', accent:'#13213a', headerBackground:'#ffffff', headerText:'#18243a', footerBackground:'#ffffff', footerText:'#62728a', sectionHeading:'#18243a', border:'#d9e2ee', mutedBackground:'#f8fafc', evidenceAccent:'#155dfc' }
export const COLOR_LABELS: Record<keyof BrandColors,string> = { primary:'Primary', accent:'Accent', headerBackground:'Header background', headerText:'Header text', footerBackground:'Footer background', footerText:'Footer text', sectionHeading:'Section heading', border:'Border', mutedBackground:'Muted background', evidenceAccent:'Evidence accent' }
const c=(x:Partial<BrandColors>):BrandColors=>({...DEFAULT_BRAND_COLORS,...x})
export const BRAND_PALETTES: Array<{name:string; description:string; colors:BrandColors}> = [
{name:'CRED Blue',description:'Default trusted service documentation.',colors:DEFAULT_BRAND_COLORS},
{name:'Slate Professional',description:'Calm B2B report tone.',colors:c({primary:'#334155',accent:'#0f172a',headerBackground:'#f8fafc',footerBackground:'#f1f5f9',border:'#cbd5e1'})},
{name:'Executive Navy',description:'Premium leadership package.',colors:c({primary:'#1d4ed8',accent:'#0f172a',headerBackground:'#0f172a',headerText:'#eff6ff',footerBackground:'#0b1120',footerText:'#bfdbfe',sectionHeading:'#1e3a8a'})},
{name:'Graphite Industrial',description:'Durable industrial documentation.',colors:c({primary:'#3f3f46',accent:'#18181b',headerBackground:'#27272a',headerText:'#fafafa',footerBackground:'#18181b',footerText:'#d4d4d8'})},
{name:'Emerald Service',description:'Clean field service brand.',colors:c({primary:'#059669',accent:'#064e3b',headerBackground:'#ecfdf5',footerBackground:'#064e3b',footerText:'#d1fae5'})},
{name:'Copper Trade',description:'Warm construction and trade style.',colors:c({primary:'#b45309',accent:'#451a03',headerBackground:'#fff7ed',border:'#fed7aa'})},
{name:'Safety Amber',description:'Safety-forward operations reports.',colors:c({primary:'#d97706',accent:'#111827',headerBackground:'#fffbeb',footerBackground:'#111827',footerText:'#fde68a'})},
{name:'Property Inspection',description:'Real estate condition report.',colors:c({primary:'#2563eb',accent:'#365314',footerBackground:'#ecfccb',footerText:'#365314'})},
{name:'Fleet Utility',description:'Vehicle and equipment service.',colors:c({primary:'#0f766e',accent:'#1f2937',footerBackground:'#1f2937',footerText:'#ccfbf1'})},
{name:'Legal Classic',description:'Formal evidence packet.',colors:c({primary:'#374151',accent:'#111827',border:'#9ca3af'})},
{name:'Clean Medical',description:'Bright clinical presentation.',colors:c({primary:'#0891b2',accent:'#155e75',headerBackground:'#ecfeff'})},
{name:'Modern Black',description:'High-end monochrome brand.',colors:c({primary:'#000000',accent:'#525252',headerBackground:'#000000',headerText:'#ffffff',footerBackground:'#000000',footerText:'#e5e5e5'})},
{name:'Soft Neutral',description:'Warm approachable paperwork.',colors:c({primary:'#78716c',accent:'#44403c',headerBackground:'#fafaf9',footerBackground:'#f5f5f4'})},
{name:'High Contrast',description:'Maximum readability.',colors:c({primary:'#1d4ed8',accent:'#000000',headerBackground:'#000000',headerText:'#ffffff',footerBackground:'#000000',footerText:'#ffffff',border:'#000000'})},
{name:'Municipal',description:'Public-sector formality.',colors:c({primary:'#1e40af',accent:'#334155'})},
{name:'Construction Orange',description:'Jobsite visibility.',colors:c({primary:'#ea580c',accent:'#111827',evidenceAccent:'#f97316'})},
{name:'Automotive OEM',description:'Fleet and dealer documentation.',colors:c({primary:'#0f172a',accent:'#b91c1c',evidenceAccent:'#b91c1c'})},
{name:'Engineering Blue',description:'Technical engineering reports.',colors:c({primary:'#0369a1',accent:'#0c4a6e',evidenceAccent:'#0284c7'})},
]
const t=(preset:TypographyPreset,name:string,description:string,headingStack:string,bodyStack=headingStack,labelStyle:TypographySettings['labelStyle']='uppercase'):TypographySettings & {name:string;description:string}=>({name,description,preset,headingStack,bodyStack,labelStyle,headingWeight:700,titleWeight:800,letterSpacing:'0',titleSpacing:'-0.02em',sectionHeadingStyle:'standard',metadataStyle:'muted',sectionHeadingLetterSpacing:'0'})
export const TYPOGRAPHY_OPTIONS: Record<TypographyPreset, TypographySettings & {name:string; description:string}> = {
professional_sans:t('professional_sans','Professional Sans','Balanced system UI style.','Inter, Arial, Helvetica, sans-serif'),modern_compact:t('modern_compact','Modern Compact','Dense modern service reports.','Arial Narrow, Arial, sans-serif','Arial, Helvetica, sans-serif'),editorial_serif:t('editorial_serif','Editorial Serif','Polished narrative documents.','Georgia, Times New Roman, serif','Arial, Helvetica, sans-serif','title'),technical_report:t('technical_report','Technical Report','Precise diagnostic formatting.','Arial, Helvetica, sans-serif','Arial, Helvetica, sans-serif','mono'),field_service:t('field_service','Field Service','Clear technician handoff.','Verdana, Geneva, sans-serif'),legal_document:t('legal_document','Legal Document','Formal serif headings.','Georgia, Times New Roman, serif','Times New Roman, Georgia, serif','title'),clean_corporate:t('clean_corporate','Clean Corporate','Executive-ready system stack.','system-ui, -apple-system, Segoe UI, sans-serif','system-ui, -apple-system, Segoe UI, sans-serif','sentence'),utility_mono_accent:t('utility_mono_accent','Utility Mono Accent','Mono labels with readable body.','Arial, Helvetica, sans-serif','Arial, Helvetica, sans-serif','mono'),government_form:t('government_form','Government Form','Structured public-sector forms.','Arial, Helvetica, sans-serif'),executive_letter:t('executive_letter','Executive Letter','Formal leadership letter style.','Georgia, Times New Roman, serif','Georgia, Times New Roman, serif','title'),inspection_notes:t('inspection_notes','Inspection Notes','Readable field annotations.','Verdana, Geneva, sans-serif'),industrial_label:t('industrial_label','Industrial Label','Bold labels and compact metadata.','Arial Black, Arial, sans-serif','Arial, Helvetica, sans-serif')}
export const REPORT_TEMPLATES = ['Modern Service Report','Classic Letterhead','Executive Summary','Inspection Binder','Legal Evidence Package','Technical Diagnostic Report','Property Condition Report','Fleet Service Report','Insurance Photo Report','Minimal Clean','Industrial Field Report','Corporate Documentation'].map((name,i)=>({name,description:`${name} presentation pack.`,palette:BRAND_PALETTES[i%BRAND_PALETTES.length].name,typography:TYPOGRAPHY_PRESETS[i%TYPOGRAPHY_PRESETS.length],header_layout:HEADER_LAYOUTS[i%HEADER_LAYOUTS.length],sectionStyle:SECTION_STYLES[i%SECTION_STYLES.length],evidenceStyle:EVIDENCE_STYLES[i%EVIDENCE_STYLES.length]})) as Array<{name:string;description:string;palette:string;typography:TypographyPreset;header_layout:HeaderLayout;sectionStyle:SectionStyle;evidenceStyle:EvidenceStyle}>
export const DEFAULT_SIGNATURE_BLOCKS: SignatureBlock[] = ['Prepared by','Reviewed by','Approved by','Customer acknowledgement'].map((label,i)=>({key:label.toLowerCase().replaceAll(' ','_'),enabled:i===0,label,typedName:null,title:null,showDate:true,useSignatureImage:i===0,showSignatureLine:true}))
export const DEFAULT_CUSTOM_FIELDS: CustomReportField[] = ['Project #','Work Order #','Claim #','Policy #','Permit #','PO #','Reference #','Invoice #','Unit #','Fleet #','Site #','Inspector ID'].map((label,i)=>({id:`field_${i}`,label,showInHeader:false,showInCover:false,showInIdentityBlock:true,showInFooter:false}))
export const DEFAULT_REPORT_STYLE: ReportStyle = { templatePack:'System default', coverPage:'none', coverImageSource:'none', showCoverLogo:true, showCoverCompanyInfo:true, showCoverTitle:true, showCoverClient:true, showCoverAsset:true, showCoverLocation:true, showCoverPreparedBy:true, showCoverDate:true, showCoverReportId:true, showCoverImage:false, showConfidentialityLabel:false, sectionStyle:'carded', showSectionLabels:true, showSectionDividers:true, showSectionNumbers:false, sectionSpacing:'standard', sectionTitleStyle:'standard', subsectionStyle:'standard', evidenceImageSize:'standard', evidenceStyle:'standard_cards', evidenceNumbering:true, evidenceAppendix:true, timestamps:true, captureMetadata:false, notes:true, location:false, fileNames:false, captions:true, pageBreaksBetweenEvidenceGroups:false, evidenceIds:true, sectionGrouping:true, showReportDate:true, showPreparedBy:true, showPageNumber:false, showGeneratedByCred:false, typedSignature:null, signatureDate:true, approvalBlock:false, reviewedByLabel:'Reviewed by', headerOptions:{showLogo:true,showCompanyName:true,showTagline:true,showContactInfo:true,showAddress:true,showPreparedBy:true,showReportId:true,showReportDate:true,showCustomer:true,showAsset:true,showLocation:true,accentBar:true,dividerLine:true}, watermark:{option:'none',text:'',opacity:'subtle',placement:'diagonal',draftOnly:false}, signatureLayout:'single_signature', signatureBlocks:DEFAULT_SIGNATURE_BLOCKS, customFields:DEFAULT_CUSTOM_FIELDS }
export const DEFAULT_BRAND_PROFILE: WorkspaceBrandProfile = { display_name:null, tagline:null, phone:null, email:null, website:null, address:null, license_number:null, certification_number:null, tax_number:null, insurance_number:null, business_hours:null, department:null, branch_location:null, prepared_by_name:null, prepared_by_title:null, logo_storage_path:null, dark_logo_storage_path:null, icon_storage_path:null, signature_storage_path:null, colors:DEFAULT_BRAND_COLORS, typography:TYPOGRAPHY_OPTIONS.professional_sans, header_layout:'classic_letterhead', footer_layout:'minimal', report_style:DEFAULT_REPORT_STYLE, footer_text:null, show_report_id:true, show_page_date:true, show_contact_info:true, show_confidentiality_note:false, show_signature_block:true }
export function isValidHexColor(value:string){ return HEX_COLOR_PATTERN.test(value.trim()) }
export function normalizeBrandProfile(row: Partial<WorkspaceBrandProfile> | null | undefined): WorkspaceBrandProfile { const preset = TYPOGRAPHY_PRESETS.includes(row?.typography?.preset as TypographyPreset) ? row?.typography?.preset as TypographyPreset : 'professional_sans'; const rawHeader = row?.header_layout as string | undefined; const header = HEADER_LAYOUTS.includes(rawHeader as HeaderLayout) ? rawHeader as HeaderLayout : rawHeader === 'classic' ? 'classic_letterhead' : rawHeader === 'compact' ? 'compact_service' : rawHeader === 'bold' ? 'bold_banner' : rawHeader === 'split' ? 'split_identity' : rawHeader === 'minimal' ? 'minimal' : 'classic_letterhead'; const rawCover = row?.report_style?.coverPage as string | undefined; const coverPage = COVER_PAGE_LAYOUTS.includes(rawCover as CoverPageLayout) ? rawCover as CoverPageLayout : rawCover === 'cover' || rawCover === 'letterhead_cover' || rawCover === 'corporate_cover' || rawCover === 'executive_cover' ? 'professional_cover' : rawCover === 'image_cover' || rawCover === 'evidence_cover' ? 'simple_cover' : DEFAULT_REPORT_STYLE.coverPage; return { ...DEFAULT_BRAND_PROFILE, ...row, colors:{...DEFAULT_BRAND_COLORS,...(row?.colors ?? {})}, typography:{...TYPOGRAPHY_OPTIONS[preset],...(row?.typography ?? {}),preset}, header_layout:header, footer_layout:FOOTER_LAYOUTS.includes(row?.footer_layout as FooterLayout)?row?.footer_layout as FooterLayout:DEFAULT_BRAND_PROFILE.footer_layout, report_style:{...DEFAULT_REPORT_STYLE,...(row?.report_style ?? {}), coverPage, watermark:{...DEFAULT_REPORT_STYLE.watermark,...(row?.report_style?.watermark ?? {})}, headerOptions:{...DEFAULT_REPORT_STYLE.headerOptions,...(row?.report_style?.headerOptions ?? {})}, signatureBlocks:row?.report_style?.signatureBlocks ?? DEFAULT_SIGNATURE_BLOCKS, customFields:row?.report_style?.customFields ?? DEFAULT_CUSTOM_FIELDS} } }
export const TYPOGRAPHY_PACK_NAMES_FOR_TESTS = [{name:'Professional Sans'},{name:'Modern Compact'},{name:'Editorial Serif'},{name:'Technical Report'},{name:'Field Service'},{name:'Legal Document'},{name:'Clean Corporate'},{name:'Utility Mono Accent'},{name:'Government Form'},{name:'Executive Letter'},{name:'Inspection Notes'},{name:'Industrial Label'}]
export const REPORT_TEMPLATE_PACK_NAMES_FOR_TESTS = [{name:'Classic Letterhead'},{name:'Modern Service Report'},{name:'Bold Banner'},{name:'Inspection Binder'},{name:'Legal Evidence Package'},{name:'Technical Diagnostic Report'},{name:'Property Condition Report'},{name:'Fleet Service Report'},{name:'Minimal Clean'},{name:'Executive Summary'},{name:'Insurance Photo Report'},{name:'Industrial Field Report'},{name:'Corporate Documentation'}]
