export const HEX_COLOR_PATTERN = /^#[0-9A-Fa-f]{6}$/
export const HEADER_LAYOUTS = ['classic','compact','bold','split','minimal'] as const
export const TYPOGRAPHY_PRESETS = ['professional_sans','editorial_serif','technical_mono','modern_compact'] as const
export type HeaderLayout = typeof HEADER_LAYOUTS[number]
export type TypographyPreset = typeof TYPOGRAPHY_PRESETS[number]
export type BrandColors = { primary:string; accent:string; headerBackground:string; headerText:string; footerBackground:string; footerText:string; sectionHeading:string; border:string }
export type ReportStyle = { sectionStyle:'carded'|'clean'; evidenceImageSize:'compact'|'standard'|'large'; evidenceNumbering:boolean; evidenceAppendix:boolean; timestamps:boolean; captureMetadata:boolean }
export type WorkspaceBrandProfile = { id?:string; organization_id?:string; display_name:string|null; tagline:string|null; phone:string|null; email:string|null; website:string|null; address:string|null; prepared_by_name:string|null; prepared_by_title:string|null; logo_storage_path:string|null; dark_logo_storage_path:string|null; icon_storage_path:string|null; signature_storage_path:string|null; colors:BrandColors; typography:{ preset:TypographyPreset }; header_layout:HeaderLayout; footer_layout:string; report_style:ReportStyle; footer_text:string|null; show_report_id:boolean; show_page_date:boolean; show_contact_info:boolean; show_confidentiality_note:boolean; show_signature_block:boolean }
export const DEFAULT_BRAND_COLORS: BrandColors = { primary:'#155dfc', accent:'#13213a', headerBackground:'#ffffff', headerText:'#18243a', footerBackground:'#ffffff', footerText:'#62728a', sectionHeading:'#18243a', border:'#d9e2ee' }
export const DEFAULT_REPORT_STYLE: ReportStyle = { sectionStyle:'carded', evidenceImageSize:'standard', evidenceNumbering:true, evidenceAppendix:true, timestamps:true, captureMetadata:false }
export const DEFAULT_BRAND_PROFILE: WorkspaceBrandProfile = { display_name:null, tagline:null, phone:null, email:null, website:null, address:null, prepared_by_name:null, prepared_by_title:null, logo_storage_path:null, dark_logo_storage_path:null, icon_storage_path:null, signature_storage_path:null, colors:DEFAULT_BRAND_COLORS, typography:{ preset:'professional_sans' }, header_layout:'classic', footer_layout:'standard', report_style:DEFAULT_REPORT_STYLE, footer_text:null, show_report_id:true, show_page_date:true, show_contact_info:true, show_confidentiality_note:false, show_signature_block:true }
export function isValidHexColor(value:string){ return HEX_COLOR_PATTERN.test(value.trim()) }
export function normalizeBrandProfile(row: Partial<WorkspaceBrandProfile> | null | undefined): WorkspaceBrandProfile { return { ...DEFAULT_BRAND_PROFILE, ...row, colors:{...DEFAULT_BRAND_COLORS,...(row?.colors ?? {})}, typography:{ preset: row?.typography?.preset ?? 'professional_sans'}, report_style:{...DEFAULT_REPORT_STYLE,...(row?.report_style ?? {})} } }
